version: "3.9"

services:
    web:
      build: ./
      ports:
        - "3000:3000"
      command: node index
      volumes:
        - ./:/digital-guafak-website
    
    # redis:
    #   container_name: redis-db
    #   image: redis:7.0.7
    #   ports:
    #     - "6379:6379"


      